# Generated by Django 2.2 on 2019-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
        ('ss_users', '0002_auto_20190416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssuser',
            name='achivements',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='comments',
            field=models.ManyToManyField(to='ss_main.Comment'),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='shirts',
            field=models.ManyToManyField(to='ss_main.Shirt'),
        ),
    ]
