# Generated by Django 2.2 on 2019-04-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_auto_20190422_1525'),
        ('ss_users', '0003_auto_20190416_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssuser',
            name='comments',
        ),
        migrations.AddField(
            model_name='ssuser',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Comment'),
        ),
        migrations.RemoveField(
            model_name='ssuser',
            name='shirts',
        ),
        migrations.AddField(
            model_name='ssuser',
            name='shirts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Shirt'),
        ),
    ]
