# Generated by Django 2.2 on 2019-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_users', '0005_auto_20190422_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssuser',
            name='comments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Comment'),
        ),
        migrations.AlterField(
            model_name='ssuser',
            name='shirts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Shirt'),
        ),
    ]
