# Generated by Django 2.2 on 2019-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_users', '0006_auto_20190422_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssuser',
            name='comments',
        ),
    ]
