# Generated by Django 2.2 on 2019-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('describcion', models.TextField(max_length=256)),
                ('tegs', models.TextField(blank=True, max_length=256, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
