# Generated by Django 2.2 on 2019-04-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ss_users', '0001_initial'),
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ss_users.SSUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shirt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Shirt'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ss_users.SSUser'),
        ),
    ]
