# Generated by Django 2.2 on 2019-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='comments',
            field=models.ManyToManyField(blank=True, to='ss_main.Comment'),
        ),
    ]
