# Generated by Django 2.2 on 2019-04-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0002_auto_20190416_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='comments',
        ),
        migrations.AddField(
            model_name='shirt',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Comment'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='describcion',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='tegs',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
