# Generated by Django 2.2 on 2019-04-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_auto_20190422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Comment'),
        ),
    ]
