# Generated by Django 2.2 on 2019-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_auto_20190423_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='base_color',
            field=models.CharField(choices=[('wt', 'white'), ('bk', 'black'), ('rd', 'red'), ('gn', 'green'), ('bl', 'blue')], default='wt', max_length=2),
        ),
        migrations.AddField(
            model_name='shirt',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='shirt',
            name='theme',
            field=models.CharField(choices=[('none', 'none'), ('love', 'love'), ('humor', 'humor'), ('trip', 'trip'), ('fear', 'fear'), ('night', 'night'), ('sadness', 'sadness'), ('disco', 'disco'), ('fog', 'fog')], default='none', max_length=8),
        ),
    ]
