# Generated by Django 2.2 on 2019-04-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_users', '0008_remove_ssuser_shirts'),
        ('ss_main', '0005_auto_20190422_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='shirt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ss_main.Shirt'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ss_users.SSUser'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ss_users.SSUser'),
        ),
    ]
